const express = require("express");
const router = express.Router();
const Orders = require("../models/Orders");


// CREATE ORDER
router.post("/add", async (req, res) => {
    try {
        const orderData = {
            user_id: req.body.user_id,
            username: req.body.username,    // store username
            order_id: req.body.order_id,    // schema will auto-generate if missing
            shipping_address: req.body.shipping_address,
            product: req.body.product
            // ETA auto-generated by schema
        };

        const newOrder = new Orders(orderData);
        const saved = await newOrder.save();

        res.status(201).json(saved);
    } catch (err) {
        console.error("Error creating order:", err);
        res.status(500).json({ error: "Failed to create order" });
    }
});


// 🔍 GET ALL ORDERS (Admin View)
router.get("/all", async (req, res) => {
    try {
        const orders = await Orders.find()
            .populate("product.product_id")
            .populate("user_id", "username email"); 
            // fetch username + email from User model

        res.json(orders);
    } catch (err) {
        console.error("Error fetching all orders:", err);
        res.status(500).json({ error: "Failed to fetch all orders" });
    }
});


// GET ALL ORDERS FOR A SPECIFIC USER
router.get("/user/:user_id", async (req, res) => {
    try {
        const orders = await Orders.find({ user_id: req.params.user_id })
            .populate("product.product_id");

        res.json(orders);
    } catch (err) {
        console.error("Error fetching user orders:", err);
        res.status(500).json({ error: "Failed to fetch user orders" });
    }
});


// GET SINGLE ORDER BY ID
router.get("/:id", async (req, res) => {
    try {
        const order = await Orders.findById(req.params.id)
            .populate("product.product_id")
            .populate("user_id", "username");

        if (!order) {
            return res.status(404).json({ error: "Order not found" });
        }

        res.json(order);
    } catch (err) {
        console.error("Error fetching order:", err);
        res.status(500).json({ error: "Failed to fetch order" });
    }
});


// DELETE ORDER
router.delete("/delete/:id", async (req, res) => {
    try {
        const deleted = await Orders.findByIdAndDelete(req.params.id);

        if (!deleted) {
            return res.status(404).json({ error: "Order not found" });
        }

        res.json({ message: "Order deleted" });
    } catch (err) {
        console.error("Error deleting order:", err);
        res.status(500).json({ error: "Failed to delete order" });
    }
});

module.exports = router;
